# Generated by Django 4.2.18 on 2025-02-05 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_oscar_razorpay.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('txnid', models.CharField(db_index=True, default=django_oscar_razorpay.models.generate_id, max_length=32)),
                ('basket_id', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('captured', 'Captured'), ('authorized', 'Authorized'), ('capfailed', 'Capture Failed'), ('authfailed', 'Authorization Failed')], default='initiated', max_length=32)),
                ('rz_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('error_code', models.CharField(blank=True, max_length=32, null=True)),
                ('error_message', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
